import { type Field, type OptionalField } from "./fields.js";

/**
 * Defines a table's column map (column name -> field definition).
 *
 * This is the TypeScript representation of what ends up being synced to the server.
 */
export type TableDefinition = Record<string, Field<unknown>>;

/**
 * Stable JSON shape produced by `Table#toJSON()`.
 *
 * The `columns` object contains Vexi `Field` instances, which themselves implement `toJSON()`.
 */
export type TableJson = {
  /**
   * Schema format version.
   *
   * Increment this when the JSON shape changes in a non-backwards compatible way.
   */
  version: 1;
  /**
   * Column definitions keyed by column name.
   */
  columns: TableDefinition;
};

/**
 * A runtime wrapper for a table definition.
 *
 * Why this exists:
 * - The CLI needs a reliable way to detect exported tables in `schema.ts`.
 * - We need stable JSON serialization to sync schema to the Rust backend.
 * - We want a single place to hang table-level metadata in future versions.
 *
 * @template Def - Column definition map for this table.
 */
export class Table<Def extends TableDefinition> {
  /**
   * Runtime marker used by the CLI to identify Vexi tables.
   * @internal
   */
  readonly isVexiTable = true;

  /**
   * Column definitions for this table.
   */
  readonly columns: Def;

  constructor(columns: Def) {
    this.columns = columns;
  }

  /**
   * Stable JSON representation used by `vexi sync`.
   */
  toJSON(): TableJson {
    return {
      version: 1,
      columns: this.columns,
    };
  }
}

/**
 * Create a table definition.
 *
 * This is intentionally similar to Zod's `z.object({...})` ergonomics, but represents a database
 * table instead of a generic runtime validator.
 *
 * @param columns - Column definitions.
 * @returns A `Table` instance (detectable at runtime + serializable).
 */
export function createTable<const Def extends TableDefinition>(
  columns: Def,
): Table<Def> {
  return new Table(columns);
}

/**
 * Helper type to improve tooltip readability in IDEs.
 * Collapses intersections and mapped types into a single object type.
 */
export type Prettify<T> = {
  [K in keyof T]: T[K];
} & {};

/**
 * Infers the TypeScript interface for a given TableDefinition.
 *
 * This type splits the keys into two groups:
 * 1. Required keys (fields that are NOT OptionalField)
 * 2. Optional keys (fields that ARE OptionalField)
 *
 * It then combines them into a single "prettified" object type.
 */
export type Infer<T> =
  T extends Field<infer Result>
    ? Result
    : Prettify<
        // Required keys
        {
          [K in keyof T as T[K] extends OptionalField<Field<unknown>>
            ? never
            : K]: T[K] extends Field<infer Result> ? Result : never;
        } & {
          // Optional keys
          [K in keyof T as T[K] extends OptionalField<Field<unknown>>
            ? K
            : never]?: T[K] extends Field<infer Result> ? Result : never;
        }
      >;

/**
 * The TypeScript shape of a stored row for a given table.
 *
 * All tables have an implicit `id: string` primary key generated by the server.
 */
export type Row<TTable extends Table<TableDefinition>> = Prettify<
  {
    id: string;
  } & Infer<TTable["columns"]>
>;

/**
 * Insert input for a table (does not include `id`).
 */
export type InsertInput<TTable extends Table<TableDefinition>> = Infer<
  TTable["columns"]
>;

/**
 * Update patch for a table (partial insert input).
 */
export type UpdatePatch<TTable extends Table<TableDefinition>> = Partial<
  InsertInput<TTable>
>;

/**
 * Search result for a table.
 */
export type SearchResult<TTable extends Table<TableDefinition>> = {
  item: Row<TTable>;
  score: number;
};
